windowrule = match:class satty, float on, center on, animation fade
windowrule = match:class Rofi, float on, animation fade
windowrule = match:class nautilus --new-window, float on, animation fade
windowrule = match:class org.gnome.Calculator, float on, center on
windowrule = match:class firefox-developer-edition, match:title Picture-in-Picture, float on, pin on
windowrule = match:class nvim, border_size 0

windowrule {
    name = vscode-max
    match:initial_class = ^(Code|code-url-handler)$
    
    maximize = 2
}
