foreground         #151529
background         #FCFFFA
cursor             #486B7B

color0             #FCFFFA
color1             #C3BDC6
color2             #7BC0CD
color3             #EB7B9A
color4             #337BCC
color5             #8E65B2
color6             #2F2F5C
color7             #151529
color8             #9EAC94
color9             #C3BDC6
color10            #7BC0CD
color11            #EB7B9A
color12            #337BCC
color13            #8E65B2
color14            #2F2F5C
color15            #07070E
