$background = rgb(FCFFFA)
$foreground = rgb(151529)
$color0 = rgb(FCFFFA)
$color1 = rgb(C3BDC6)
$color2 = rgb(7BC0CD)
$color3 = rgb(EB7B9A)
$color4 = rgb(337BCC)
$color5 = rgb(8E65B2)
$color6 = rgb(2F2F5C)
$color7 = rgb(151529)
$color8 = rgb(9EAC94)
